define({
  root: ({
    _widgetLabel: "Smart Editor",
    noEditPrivileges: "Your account does not have permission to create or modify data.",
    widgetActive: "Active",
    widgetNotActive: "Not Active",
    pressStr: "Press ",
    ctrlStr: " CTRL ",
    snapStr: " to enable snapping",
    noAvailableTempaltes: "No available templates",
    editorCache: " - Editor Cache",
    presetFieldAlias: "Field",
    presetValue: "Preset Value",
    usePresetValues: " Use Preset Values (New features only)",
    editGeometry: " Edit Geometry",
    savePromptTitle: "Save feature",
    savePrompt: "Would you like to save the current feature?",
    deletePromptTitle: "Delete feature",
    deletePrompt: "Are you sure you want to delete the selected feature?",
    attachmentLoadingError: "Error uploading attachments",
    noConfiguredLayers: "No editable layers configured",
    editorPopupTitle: "Batch Attribute Editor",
    editorPopupSaveBtn: "Save",
    editorPopupMultipleValues: "",
    clear: "Clear",
    featuresUpdated: "${0} / ${1} feature(s) updated",
    featuresSelected: "${0} feature(s) selected",
    featuresSkipped: "Bypassed",
    search: "Search",
    queryInput: "Enter value to query",
    noFilterTip: "Without filter expression defined, this query task will list all features in the specified data source.",
    setFilterTip: "Please set filter correctly.",
    filterPopup: "Filter Layer",
    cancel: "Cancel",
    noValue: "No Value",
    emptyString: "Empty String",
    existingValue: "Keep Existing Value",
    newDate: "New Date",
    valueChooser: "Select/Type a Value",
    layerTable: {
      colLabel: "Layer Name",
      numSelected: "#",
      colSyncStatus: ""
    },
    attachmentSaveDeleteWarning: "Warning: Changes to attachments are saved automatically",
    drawBox: {
      point: "Point",
      line: "Line",
      polyline: "Polyline",
      freehandPolyline: "Freehand Polyline",
      extent: "Extent",
      polygon: "Polygon",
      freehandPolygon: "Freehand Polygon",
      clear: "Clear",
      addPointToolTip: "Click to select in this area",
      addShapeToolTip: "Draw a shape to select features",
      freehandToolTip: "Press and hold to draw a shape to select features",
      startToolTip: "Draw a shape to select features"
    },
    filterEditor: {
      all: "All",
      noAvailableTempaltes: "No available templates",
      searchTemplates: "Search Templates"
    },
    invalidConfiguration: "Widget is either not configured or the layers in the configuration are no longer in the map.  Please open the app in the builder mode and reconfigure the widget."
  }),
  "ar": 1,
  "bs": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hr": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});